services:
  backend:
    container_name: e_recycler_api
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DB_USER: ${DB_E_RECYCLER_USER}
      DB_USER_PASSWORD: ${DB_E_RECYCLER_USER_PASSWORD}
      DB_DATABASE_NAME: ${DB_E_RECYCLER_DATABASE_NAME}
      DB_PORT: 3306
      DB_HOSTNAME: db-app
      AUTH_SERVICE_URL: "http://localhost:5000"
    depends_on:
      - db-app
    ports:
      - ${E_RECYCLER_PORT}:8080
    networks:
      - e-recycler-net

  auth:
    container_name: auth_api
    build:
      context: ./auth/
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_TIMEOUT: ${ACCESS_TOKEN_TIMEOUT}
      DB_AUTH_USER: ${DB_AUTH_USER}
      DB_AUTH_USER_PASSWORD: ${DB_AUTH_USER_PASSWORD}
      DB_AUTH_DATABASE_NAME: ${DB_AUTH_DATABASE_NAME}
      DB_AUTH_PORT: 3306
      DB_AUTH_HOSTNAME: db-auth
    depends_on:
      - db-auth
    ports:
      - ${AUTH_PORT}:8080
    networks:
      - e-recycler-net

  db-app:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_E_RECYCLER_ROOT_PASSWORD}
      MYSQL_USER: ${DB_E_RECYCLER_USER}
      MYSQL_PASSWORD: ${DB_E_RECYCLER_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_E_RECYCLER_DATABASE_NAME}
    ports:
      - ${DB_E_RECYCLER_PORT}:3306
    volumes:
      - erecycler-data:/var/lib/mysql
    networks:
      - e-recycler-net

  db-auth:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_AUTH_ROOT_PASSWORD}
      MYSQL_USER: ${DB_AUTH_USER}
      MYSQL_PASSWORD: ${DB_AUTH_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_AUTH_DATABASE_NAME}
    ports:
      - ${DB_AUTH_PORT}:3306
    volumes:
      - auth-data:/var/lib/mysql
    networks:
      - e-recycler-net

volumes:
  erecycler-data:
  auth-data:
networks:
  e-recycler-net: {}
